apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: helloworld
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 450Mi