apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployer
rules:
- apiGroups: ["extensions", "apps"] # "" indicates the core API group
  resources: ["pods","deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-pods
subjects:
- kind: User
  name: system:serviceaccount:jenkins:default 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-deployer
  apiGroup: rbac.authorization.k8s.io